ped: ped.ped  # a PED pedigree file for PhaseByTransmission
refseq:    /mnt/isilon/cbmi/variome/reference/human/hg19/hg19.fa
refseqidx: /mnt/isilon/cbmi/variome/reference/human/hg19/hg19.nix
siv:       /mnt/isilon/cbmi/variome/reference/human/GRCh38/Mills_and_1000G_gold_standard.indels.b38.primary_assembly.vcf.gz

buildve: hg38
pedfile: pedfile.txt

projdir: /mnt/isilon/cbmi/variome/leipzig/GRIN
# subdirectories relative to projdir
datadirs:
    fastq:            fastq
    samples:          samples
    fastqc:           fastqc
    sams:             sams
    bams:             bams
    picard:           picard
    realigned:        realigned
    lists:            lists
    recalibrated:     recalibrated
    postrecalibrated: postrecalibrated
    pdfs:             pdfs
    gvcfs:            gvcfs
    log:              log 

# !!python/object/apply:os.path.join

tools:
    java:
        /mnt/isilon/cbmi/variome/bin/java
    # must be set separately from java because java will be treated as input
    javaopts: -Xmx32g -Xms16g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/
    seq2qc:
        /mnt/isilon/cbmi/variome/bin/fastqc
    sam2bam:
        /mnt/isilon/cbmi/variome/bin/samtools
    sortbam:
        /mnt/isilon/cbmi/variome/bin/novosort
    makesam:
        /mnt/isilon/cbmi/variome/bin/novoalign

jars:
    picard:
        /mnt/isilon/cbmi/variome/bin/picard-1.57.jar
    markduplicates:
        /mnt/isilon/cbmi/variome/bin/picard/MarkDuplicates.jar
    buildbamindex:
        /mnt/isilon/cbmi/variome/bin/picard/BuildBamIndex.jar
    addorreplacereadgroups:
        /mnt/isilon/cbmi/variome/bin/picard/AddOrReplaceReadGroups.jar
    gatk:
        /mnt/isilon/cbmi/variome/bin/GATK/GenomeAnalysisTK.jar
    snpeff:
        /mnt/isilon/cbmi/variome/bin/snpeff/4.0/snpEff.jar
    snpeffcnf:
        /mnt/isilon/cbmi/variome/bin/snpeff/4.0/snpEff.config

