admins: leipzig@gmail.com
#zhangs3@email.chop.edu
ped: ped.ped  # a PED pedigree file for PhaseByTransmission
ref:    /mnt/isilon/cbmi/variome/reference/human/GRCh38/genome.fa
refidx: /mnt/isilon/cbmi/variome/reference/human/GRCh38/genome.idx
known:       /mnt/isilon/cbmi/variome/reference/human/GRCh38/Mills_and_1000G_gold_standard.indels.b38.primary_assembly.vcf.gz
#tabixed this:
dbsnp: /mnt/isilon/cbmi/variome/reference/human/GRCh38/dbSNP/All_20151104.vcf.gz
buildve: hg38
sample_table: sample_table.txt
pedfile: samples.ped

projdir: /mnt/lustre/users/leipzigj/GRIN/

# subdirectories relative to projdir
datadirs:
    fastq:            fastq
    samples:          samples
    fastqc:           fastqc
    sams:             sams
    bams:             bams
    picard:           picard
    realigned:        realigned
    lists:            lists
    recalibrated:     recalibrated
    postrecalibrated: postrecalibrated
    pdfs:             pdfs
    gvcfs:            gvcfs
    vcfs:             vcfs
    gemini:           gemini
    log:              logs

# !!python/object/apply:os.path.join

tools:
    java:
        /mnt/isilon/cbmi/variome/bin/java
    # must be set separately from java because java will be treated as input
    javaopts: -Xmx32g -Xms16g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/
    seq2qc:
        /mnt/isilon/cbmi/variome/bin/fastqc
    samtools:
        /mnt/isilon/cbmi/variome/bin/samtools
    sortbam:
        /mnt/isilon/cbmi/variome/bin/novosort
    align:
        /mnt/isilon/cbmi/variome/bin/novoalign
    vt:
        /mnt/isilon/cbmi/variome/bin/vt/vt
    tabix:
        /mnt/isilon/cbmi/variome/bin/tabix
    bgzip:
        /mnt/isilon/cbmi/variome/bin/bgzip
    gemini:
        /mnt/isilon/cbmi/variome/bin/gemini/bin/gemini
jars:
    picard:
        path:
            /mnt/isilon/cbmi/variome/bin/picard-tools-2.0.1/picard.jar
        markdups:
            MarkDuplicates
        index:
            BuildBamIndex
        readgroups:
            AddOrReplaceReadGroups
    gatk:
        /mnt/isilon/cbmi/variome/bin/GATK/GenomeAnalysisTK.jar
    snpeff:
        path:
            /mnt/isilon/cbmi/variome/bin/snpeff/4.0/snpEff.jar
        cnf:
            /mnt/isilon/cbmi/variome/bin/snpeff/4.0/snpEff.GRCh38.config
        db:
            GRCh38.76
        ud:
            10
        format:
            -classic