admins: leipzig@gmail.com
#zhangs3@email.chop.edu
ref:    /mnt/isilon/cbmi/variome/reference/human/GRCh38/genome.fa
refidx: /mnt/isilon/cbmi/variome/reference/human/GRCh38/genome.idx
known:       /mnt/isilon/cbmi/variome/reference/human/GRCh38/Mills_and_1000G_gold_standard.indels.b38.primary_assembly.vcf.gz
#tabixed this:
dbsnp: /mnt/isilon/cbmi/variome/reference/human/GRCh38/dbSNP/All_20151104.vcf.gz
buildve: hg38

# subdirectories relative to projdir
datadirs:
    fastq:            fastq
    samples:          samples
    fastqc:           qc/fastqc
    sams:             GRCh38/sams
    bams:             GRCh38/bams
    picard:           GRCh38/picard
    realigned:        GRCh38/realigned
    lists:            GRCh38/lists
    recalibrated:     GRCh38/recalibrated
    postrecalibrated: GRCh38/postrecalibrated
    pdfs:             GRCh38/pdfs
    gvcfs:            GRCh38/gvcfs
    vcfs:             GRCh38/vcfs
    vtpeek:           GRCh38/qc/vcf
    gemini:           GRCh38/gemini
    analysis:         GRCh38/analysis
    log:              logs

analysis:
    rlibrary:
        /mnt/isilon/cbmi/variome/leipzig/R/x86_64-redhat-linux-gnu-library/3.2
    bsgenome:
        BSgenome.Hsapiens.UCSC.hg38
    txdb:
        TxDb.Hsapiens.UCSC.hg38.knownGene
    snpdb:
        SNPlocs.Hsapiens.dbSNP144.GRCh38
    esp:
        MafDb.ESP6500SI.V2.SSA137
    exac:
        MafDb.ExAC.r0.3.sites
    sift:
        SIFT.Hsapiens.dbSNP137
    phylo:
        humanGenesPhylostrata
