admins: leipzig@gmail.com
#zhangs3@email.chop.edu
ref:    /mnt/isilon/cbmi/variome/reference/human/g1k_v37/human_g1k_v37.fasta.gz
refidx: /mnt/isilon/cbmi/variome/reference/human/g1k_v37/human_g1k_v37.nix
known:       /mnt/isilon/cbmi/variome/reference/human/Mills_and_1000G_gold_standard.indels.b37.sites.vcf
#tabixed this:
dbsnp: /mnt/isilon/cbmi/variome/reference/human/GrCH37/dbSNP146.GRCh37.vcf.gz
buildve: hg37

# subdirectories relative to projdir
datadirs:
    fastq:            fastq
    samples:          samples
    fastqc:           qc/fastqc
    sams:             GRCh37/sams
    bams:             GRCh37/bams
    picard:           GRCh37/picard
    realigned:        GRCh37/realigned
    lists:            GRCh37/lists
    recalibrated:     GRCh37/recalibrated
    postrecalibrated: GRCh37/postrecalibrated
    pdfs:             GRCh37/pdfs
    gvcfs:            GRCh37/gvcfs
    vcfs:             GRCh37/vcfs
    vtpeek:           GRCh37/qc/vcf
    gemini:           GRCh37/gemini
    log:              logs

jars:
    picard:
        path:
            /mnt/isilon/cbmi/variome/bin/picard-tools-2.0.1/picard.jar
        markdups:
            MarkDuplicates
        index:
            BuildBamIndex
        readgroups:
            AddOrReplaceReadGroups
    gatk:
        /mnt/isilon/cbmi/variome/bin/GATK/GenomeAnalysisTK.jar
    snpeff:
        path:
            /mnt/isilon/cbmi/variome/bin/snpeff/4.0/snpEff.jar
        cnf:
            /mnt/isilon/cbmi/variome/bin/snpeff/4.0/snpEff.GRCh37.config
        db:
            GRCh37.75
        ud:
            '10'
        format:
            -classic

