admins: leipzig@gmail.com
#zhangs3@email.chop.edu
ped: ped.ped  # a PED pedigree file for PhaseByTransmission
ref:    /mnt/isilon/cbmi/variome/reference/human/g1k_v37/human_g1k_v37.fasta.gz
refidx: /mnt/isilon/cbmi/variome/reference/human/g1k_v37/human_g1k_v37.nix
known:       /mnt/isilon/cbmi/variome/reference/human/Mills_and_1000G_gold_standard.indels.b37.sites.vcf
#tabixed this:
dbsnp: /mnt/isilon/cbmi/variome/reference/human/GrCH37/dbSNP146.GRCh37.vcf.gz
buildve: hg19
sample_table: sample_table.txt
pedfile: samples.ped

projdir: /mnt/lustre/users/leipzigj/GRIN/

# subdirectories relative to projdir
datadirs:
    fastq:            fastq
    samples:          samples
    fastqc:           qc/fastqc
    sams:             GRCh37/sams
    bams:             GRCh37/bams
    picard:           GRCh37/picard
    realigned:        GRCh37/realigned
    lists:            GRCh37/lists
    recalibrated:     GRCh37/recalibrated
    postrecalibrated: GRCh37/postrecalibrated
    pdfs:             GRCh37/pdfs
    gvcfs:            GRCh37/gvcfs
    vcfs:             GRCh37/vcfs
    vtpeek:           GRCh37/qc/vcf
    gemini:           GRCh37/gemini
    analysis:         GRCh37/analysis
    log:              logs
# !!python/object/apply:os.path.join

tools:
    java:
        /mnt/isilon/cbmi/variome/bin/java
    # must be set separately from java because java will be treated as input
    javaopts: -Xmx32g -Xms16g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/
    seq2qc:
        /mnt/isilon/cbmi/variome/bin/fastqc
    samtools:
        /mnt/isilon/cbmi/variome/bin/samtools
    sortbam:
        /mnt/isilon/cbmi/variome/bin/novosort
    align:
        /mnt/isilon/cbmi/variome/bin/novoalign
    vt:
        /mnt/isilon/cbmi/variome/bin/vt/vt
    tabix:
        /mnt/isilon/cbmi/variome/bin/tabix
    bgzip:
        /mnt/isilon/cbmi/variome/bin/bgzip
    gemini:
        /mnt/isilon/cbmi/variome/bin/gemini/bin/gemini
jars:
    picard:
        path:
            /mnt/isilon/cbmi/variome/bin/picard-tools-2.0.1/picard.jar
        markdups:
            MarkDuplicates
        index:
            BuildBamIndex
        readgroups:
            AddOrReplaceReadGroups
    gatk:
        /mnt/isilon/cbmi/variome/bin/GATK/GenomeAnalysisTK.jar
    snpeff:
        path:
            /mnt/isilon/cbmi/variome/bin/snpeff/4.0/snpEff.jar
        cnf:
            /mnt/isilon/cbmi/variome/bin/snpeff/4.0/snpEff.GRCh38.config
        db:
            GRCh37.75
        ud:
            '10'
        format:
            -classic
analysis:
    rlibrary:
        /mnt/isilon/cbmi/variome/leipzig/R/x86_64-redhat-linux-gnu-library/3.2
    bsgenome:
        BSgenome.Hsapiens.UCSC.hg19
    txdb:
        TxDb.Hsapiens.UCSC.hg19.knownGene
    snpdb:
        SNPlocs.Hsapiens.dbSNP144.GRCh37
    esp:
        MafDb.ESP6500SI.V2.SSA137
    exac:
        MafDb.ExAC.r0.3.sites
    sift:
        SIFT.Hsapiens.dbSNP137
    phylo:
        humanGenesPhylostrata