__default__: 
  h_vmem: 4G
  mem_free: 3G
  m_mem_free: 2G
fastqc: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
align: 
  h_vmem: 3G
  mem_free: 2G
  m_mem_free: 2G
sam_to_bam: 
  h_vmem: 3G
  mem_free: 2G
  m_mem_free: 2G
merge_lanes: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
depth_of_coverage:
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
index_bam: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
ad_vcf: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
decompose_for_gemini: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
normalize_for_gemini: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
vcf_qt: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
vcf_profile: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
run_multiqc: 
  h_vmem: 20G
  mem_free: 16G
  m_mem_free: 14G
table_annovar: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
run_annovar: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
vcf2avinput: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
install_annovar_db: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
tabix: 
  h_vmem: 20G
  mem_free: 16G
  m_mem_free: 14G
gemini_db: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
variantAnalysisSetupUind: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
variantAnalysisSetupDeNovo: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
variantAnalysisAll: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
variantAnalysisDeNovo: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
compress_vcf: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
  reference: http://www.real-world-systems.com/docs/gzip.1.html
gzip: 
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
  reference: http://www.real-world-systems.com/docs/gzip.1.html
novosortbam: 
  h_vmem: 2G
  mem_free: 2G
  m_mem_free: 2G
  reference: http://www.novocraft.com/documentation/novosort-2/
target_list: 
  h_vmem: 3G
  mem_free: 2G
  m_mem_free: 2G
  #h_vmem: 55G
  #mem_free: 44G
  #m_mem_free: 40G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
extractreads: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
realign_target: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
generate_recalibration_table: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
recalibrate_bam: 
  h_vmem: 7G
  mem_free: 5G
  m_mem_free: 4G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
post_recalibrated_table: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
analyze_bqsr: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
mark_duplicates: 
  h_vmem: 60G
  mem_free: 48G
  m_mem_free: 42G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
add_readgroup: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
bam_to_gvcf: 
  h_vmem: 64G
  mem_free: 56G
  m_mem_free: 49G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
trio_vcfs: 
  h_vmem: 7G
  mem_free: 5G
  m_mem_free: 4G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
family_vcfs: 
  h_vmem: 7G
  mem_free: 5G
  m_mem_free: 4G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
run_phase_by_transmission: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_combine_variants: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
run_snpeff: 
  h_vmem: 55G
  mem_free: 44G
  m_mem_free: 38G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_snps_only: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_indels_only: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_hard_filtration_snps: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_hard_filtration_indels: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
select_passing: 
  h_vmem: 30G
  mem_free: 24G
  m_mem_free: 21G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
testR:
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
variantAnalysisDeNovo:
  h_vmem: 10G
  mem_free: 8G
  m_mem_free: 7G
variantAnalysisModels:
  h_vmem: 20G
  mem_free: 16G
  m_mem_free: 14G
variantAnalysisSetupModel:
  h_vmem: 20G
  mem_free: 16G
  m_mem_free: 14G
run_vep: 
  h_vmem: 64G
  mem_free: 56G
  m_mem_free: 49G
left_align_indels:
  h_vem: 20G
  mem_free: 16G
  m_mem_free: 41G
