__default__: 
  mem: 4G
fastqc: 
  mem: 10G
align: 
  mem: 3G
sam_to_bam: 
  mem: 3G
merge_lanes: 
  mem: 30G
make_index: 
  mem: 10G
ad_vcf: 
  mem: 10G
decompose_for_gemini: 
  mem: 10G
normalize_for_gemini: 
  mem: 10G
vcf_qt: 
  mem: 10G
vcf_profile: 
  mem: 10G
run_multiqc: 
  mem: 20G
table_annovar: 
  mem: 30G
run_annovar: 
  mem: 30G
vcf2avinput: 
  mem: 30G
install_annovar_db: 
  mem: 30G
tabix: 
  mem: 20G
gemini_db: 
  mem: 30G
variantAnalysisSetupUind: 
  mem: 30G
variantAnalysisSetupDeNovo: 
  mem: 30G
variantAnalysisAll: 
  mem: 30G
variantAnalysisDeNovo: 
  mem: 30G
compress_vcf: 
  mem: 10G
  reference: http://www.real-world-systems.com/docs/gzip.1.html
gzip: 
  mem: 10G
  reference: http://www.real-world-systems.com/docs/gzip.1.html
novosortbam: 
  mem: 1G
  reference: http://www.novocraft.com/documentation/novosort-2/
target_list: 
  mem: 3G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
extractreads: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
realign_target: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
generate_recalibration_table: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
recalibrate_bam: 
  mem: 7G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
post_recalibrated_table: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
analyze_bqsr: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
mark_duplicates: 
  mem: 60G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
add_readgroup: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
make_gvcf: 
  mem: 70G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
trio_vcfs: 
  mem: 7G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
family_vcfs: 
  mem: 7G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
run_phase_by_transmission: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_combine_variants: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
run_snpeff: 
  mem: 55G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_snps_only: 
  mem: 30G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_indels_only: 
  mem: 30G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_hard_filtration_snps: 
  mem: 30G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
gatk_hard_filtration_indels: 
  mem: 30G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
select_passing: 
  mem: 30G
  reference: https://www.broadinstitute.org/gatk/guide/article?id=1975
testR:
  mem: 10G
variantAnalysisDeNovo:
  mem: 10G
variantAnalysisModels:
  mem: 20G
variantAnalysisSetupModel:
  mem: 20G