admins: leipzig@gmail.com
#zhangs3@email.chop.edu
ped: ped.ped  # a PED pedigree file for PhaseByTransmission
ref:    /mnt/isilon/cbmi/variome/reference/human/GRCh38/genome.fa
refidx: /mnt/isilon/cbmi/variome/reference/human/GRCh38/genome.idx
known:       /mnt/isilon/cbmi/variome/reference/human/GRCh38/Mills_and_1000G_gold_standard.indels.b38.primary_assembly.vcf.gz
#tabixed this:
dbsnp: /mnt/isilon/cbmi/variome/reference/human/GRCh38/dbSNP/All_20151104.vcf.gz
buildve: hg38
sample_table: metadata/sample_table.txt
pedfile: metadata/samples.ped

projdir: /mnt/isilon/cbmi/variome/leipzig/GRIN/
summary_fastqc: /mnt/lustre/users/leipzigj/GRIN/summary_fastqc

# subdirectories relative to projdir
datadirs:
    multiqc:          multiqc
    oldbams:          oldbams
    fastq:            fastq
    samples:          samples
    fastqc:           qc/fastqc
    sams:             lustre/GRCh38/sams
    bams:             lustre/GRCh38/bams
    picard:           lustre/GRCh38/picard
    realigned:        lustre/GRCh38/realigned
    lists:            lustre/GRCh38/lists
    recalibrated:     lustre/GRCh38/recalibrated
    postrecalibrated: lustre/GRCh38/postrecalibrated
    pdfs:             lustre/GRCh38/pdfs
    gvcfs:            lustre/GRCh38/gvcfs
    vcfs:             lustre/GRCh38/vcfs
    vtpeek:           lustre/GRCh38/qc/vcf
    gemini:           lustre/GRCh38/gemini
    analysis:         GRCh38/analysis
    website:          site
    log:              logs

python3_environment: /home/leipzigj/miniconda3/envs/grinenv/bin/
python2_environment: /home/leipzigj/miniconda3/envs/geminienv/bin/

load_python3_environment: source /home/leipzigj/miniconda3/envs/grinenv/bin/activate grinenv

tools:
    java:
        java
    # must be set separately from java because java will be treated as input
    opts:
        stratospheric:
            '-Xmx80g -Xms40g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        veryhigh:
            '-Xmx64g -Xms32g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        high:
            '-Xmx48g -Xms24g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        med:
            '-Xmx32g -Xms16g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        low:
            '-Xmx16g -Xms8g  -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
    seq2qc:
        fastqc
    samtools:
        samtools
    sortbam:
        novosort
    align:
        novoalign
    vt:
        vt
    tabix:
        tabix
    bgzip:
        bgzip
    gemini:
        gemini
    multiqc:
        multiqc
jars:
    picard:
        path:
            picard
        markdups:
            MarkDuplicates
        index:
            BuildBamIndex
        readgroups:
            AddOrReplaceReadGroups
        samtofastq:
            SamToFastq
    gatk:
        /mnt/isilon/cbmi/variome/bin/GATK/GenomeAnalysisTK.jar
    snpeff:
        path:
            snpEff
        cnf:
            configs/snpEff.GRCh38.4.2.config
        db:
            GRCh38.82
        ud:
            '10'
        format:
            -classic
analysis:
    rlibrary:
        /mnt/isilon/cbmi/variome/leipzig/R/x86_64-redhat-linux-gnu-library/3.2
    bsgenome:
        BSgenome.Hsapiens.UCSC.hg38
    txdb:
        TxDb.Hsapiens.UCSC.hg38.knownGene
    snpdb:
        SNPlocs.Hsapiens.dbSNP144.GRCh38
    esp:
        MafDb.ESP6500SI.V2.SSA137
    exac:
        MafDb.ExAC.r0.3.sites
    sift:
        SIFT.Hsapiens.dbSNP137
    phylo:
        humanGenesPhylostrata
