admins: leipzig@gmail.com
#zhangs3@email.chop.edu
#
 
buildve: hg38  # should just change this parameter for different genome reference

python3_environment: grinenv
python2_environment: geminienv
load_python3_environment: source activate grinenv
tmpdir: /mnt/lustre/users/leipzigj

ped: ped.ped  # a PED pedigree file for PhaseByTransmission
#tabixed this:
dbsnp: /mnt/isilon/cbmi/variome/reference/human/GRCh38/dbSNP/All_20151104.vcf.gz
sample_table: metadata/sample_table.txt
pedfile: metadata/samples.ped

projdir: /mnt/isilon/cbmi/variome/leipzig/GRIN/
summary_fastqc: /mnt/lustre/users/leipzigj/GRIN/summary_fastqc
xbrowse: /mnt/isilon/cbmi/variome/bin/xbrowse
vepdir: /mnt/isilon/cbmi/variome/vep

xbrowse:      # for xbrowse project.yaml
    id: grin
    name: GRIN

grc_name:
    hg37: GRCh37
    hg38: GRCh38

known:
    hg37:
        /mnt/isilon/cbmi/variome/reference/human/Mills_and_1000G_gold_standard.indels.b37.sites.vcf
    hg38:
        /mnt/isilon/cbmi/variome/reference/human/GRCh38/Mills_and_1000G_gold_standard.indels.b38.primary_assembly.vcf.gz

ref:
    hg37:
        /mnt/isilon/cbmi/variome/reference/human/g1k_v37/human_g1k_v37.fasta
    hg38:
        /mnt/isilon/cbmi/variome/reference/human/GRCh38/genome.fa

refidx:
    hg37:   # created with novoindex -k 14 -s 1 human_g1k_v37.fasta.idx human_g1k_v37.fasta
        /mnt/isilon/cbmi/variome/reference/human/g1k_v37/human_g1k_v37.fasta.idx
    hg38:
        /mnt/isilon/cbmi/variome/reference/human/GRCh38/genome.idx

vepgenomes:
    hg37:
        /mnt/isilon/cbmi/variome/vep/homo_sapiens/84_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa
    hg38:
        /mnt/isilon/cbmi/variome/vep/homo_sapiens/84_GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa

# subdirectories relative to projdir
datadirs:
    multiqc:          multiqc
    oldbams:          oldbams
    fastq:            fastq
    samples:          samples
    fastqc:           fastqc
    website:          site
    log:              logs

types:
    hg37:             lustre/GRCh37/
    hg38:             lustre/GRCh38/

results:
    sams:             sams
    bams:             bams
    picard:           picard
    realigned:        realigned
    lists:            lists
    recalibrated:     recalibrated
    postrecalibrated: postrecalibrated
    pdfs:             pdfs
    gvcfs:            gvcfs
    vep:              vep
    vtpeek:           vcf
    gemini:           gemini
    vcfs:             vcfs
    analysis:         analysis


tools:
    java:
        java
    # must be set separately from java because java will be treated as input
    opts:
        stratospheric:
            '-Xmx80g -Xms40g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        veryhigh:
            '-Xmx64g -Xms32g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        high:
            '-Xmx48g -Xms24g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        med:
            '-Xmx32g -Xms16g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        low:
            '-Xmx16g -Xms8g  -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
    seq2qc:
        fastqc
    samtools:
        samtools
    sortbam:
        novosort
    align:
        novoalign
    vt:
        vt
    tabix:
        tabix
    bgzip:
        bgzip
    gemini:
        /mnt/isilon/cbmi/variome/bin/gemini/bin/gemini
    vep:
        /mnt/isilon/cbmi/variome/bin/ensembl-tools-release-84/scripts/variant_effect_predictor/variant_effect_predictor.pl
    multiqc:
        multiqc
    annotate_variation:
        annotate_variation.pl
    table_annovar:
        table_annovar.pl
    vcf2avinput:
        convert2annovar.pl

jars:
    picard:
        path:
            /mnt/isilon/cbmi/variome/bin/picard-tools-2.0.1/picard.jar
        markdups:
            MarkDuplicates
        index:
            BuildBamIndex
        readgroups:
            AddOrReplaceReadGroups
        samtofastq:
            SamToFastq
    gatk:
        /mnt/isilon/cbmi/variome/bin/GATK/GenomeAnalysisTK.jar
    snpeff:
        path:
            snpEff
        cnf:
            configs/snpEff.GRCh38.4.2.config
        db:
            GRCh38.82
        ud:
            '10'
        format:
            -classic
analysis:
    bsgenome:
        hg37: BSgenome.Hsapiens.UCSC.hg19
        hg38: BSgenome.Hsapiens.UCSC.hg38
    txdb:
        hg37: TxDb.Hsapiens.UCSC.hg19.knownGene
        hg38: TxDb.Hsapiens.UCSC.hg38.knownGene
    snpdb:
        hg37: SNPlocs.Hsapiens.dbSNP144.GRCh37
        hg38: SNPlocs.Hsapiens.dbSNP144.GRCh38
    esp:
        hg37: MafDb.ESP6500SI.V2.SSA137
        hg38: MafDb.ESP6500SI.V2.SSA137
    exac:
        hg37: MafDb.ExAC.r0.3.sites
        hg38: MafDb.ExAC.r0.3.sites
    sift:
        hg37: SIFT.Hsapiens.dbSNP137
        hg38: SIFT.Hsapiens.dbSNP137
    phylo:
        hg37: humanGenesPhylostrata
        hg38: humanGenesPhylostrata

