admins: leipzig@gmail.com
#zhangs3@email.chop.edu
ped: ped.ped  # a PED pedigree file for PhaseByTransmission
ref:    /mnt/isilon/cbmi/variome/reference/human/g1k_v37/human_g1k_v37.fasta.gz
refidx: /mnt/isilon/cbmi/variome/reference/human/g1k_v37/human_g1k_v37.nix
known:       /mnt/isilon/cbmi/variome/reference/human/Mills_and_1000G_gold_standard.indels.b37.sites.vcf
#tabixed this:
dbsnp: /mnt/isilon/cbmi/variome/reference/human/GrCH37/dbSNP146.GRCh37.vcf.gz
buildve: hg19
sample_table: metadata/sample_table.txt
pedfile: metadata/samples.ped

projdir: /mnt/isilon/cbmi/variome/leipzig/GRIN/
summary_fastqc: /mnt/lustre/users/leipzigj/GRIN/summary_fastqc

# subdirectories relative to projdir
datadirs:
    multiqc:          multiqc
    oldbams:          oldbams
    fastq:            fastq
    samples:          samples
    fastqc:           qc/fastqc
    sams:             lustre/GRCh37/sams
    bams:             lustre/GRCh37/bams
    picard:           lustre/GRCh37/picard
    realigned:        lustre/GRCh37/realigned
    lists:            lustre/GRCh37/lists
    recalibrated:     lustre/GRCh37/recalibrated
    postrecalibrated: lustre/GRCh37/postrecalibrated
    pdfs:             lustre/GRCh37/pdfs
    gvcfs:            lustre/GRCh37/gvcfs
    vcfs:             GRCh37/vcfs
    vtpeek:           lustre/GRCh37/qc/vcf
    gemini:           lustre/GRCh37/gemini
    analysis:         GRCh37/analysis
    website:          site
    log:              logs

python3_environment: /home/leipzigj/miniconda3/envs/grinenv/bin/
python2_environment: /home/leipzigj/miniconda3/envs/geminienv/bin/

load_python3_environment: source /home/leipzigj/miniconda3/envs/grinenv/bin/activate grinenv

tools:
    java:
        java
    # must be set separately from java because java will be treated as input
    opts:
        stratospheric:
            '-Xmx80g -Xms40g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        veryhigh:
            '-Xmx64g -Xms32g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        high:
            '-Xmx48g -Xms24g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        med:
            '-Xmx32g -Xms16g -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
        low:
            '-Xmx16g -Xms8g  -Djava.io.tmpdir=/mnt/lustre/users/leipzigj/'
    seq2qc:
        fastqc
    samtools:
        samtools
    sortbam:
        novosort
    align:
        novoalign
    vt:
        vt
    tabix:
        tabix
    bgzip:
        bgzip
    gemini:
        gemini
    multiqc:
        multiqc
jars:
    picard:
        path:
            picard
        markdups:
            MarkDuplicates
        index:
            BuildBamIndex
        readgroups:
            AddOrReplaceReadGroups
        samtofastq:
            SamToFastq
    gatk:
        /mnt/isilon/cbmi/variome/bin/GATK/GenomeAnalysisTK.jar
    snpeff:
        path:
            snpEff
        cnf:
            configs/snpEff.GRCh37.4.2.config
        db:
            GRCh37.75
        ud:
            '10'
        format:
            -classic
analysis:
    bsgenome:
        BSgenome.Hsapiens.UCSC.hg19
    txdb:
        TxDb.Hsapiens.UCSC.hg19.knownGene
    snpdb:
        SNPlocs.Hsapiens.dbSNP144.GRCh37
    esp:
        MafDb.ESP6500SI.V2.SSA137
    exac:
        MafDb.ExAC.r0.3.sites
    sift:
        SIFT.Hsapiens.dbSNP137
    phylo:
        humanGenesPhylostrata
