# customized settings for a project
 
projdir: /projects/data/grin        # directory for the project

admins: zhangs3@email.chop.edu      # to receive notification of success or fail
tmpdir: /mnt/lustre/users/zhangs3   # for some tools to create temporary files

freeze: hg38  # must specify the freeze, hg37 or hg38

load_python3_environment: source activate grinenv  # default environment

summary_fastqc: /projects/data/grin/summary_fastqc

xbrowse_project:      # for xbrowse project.yaml
    id: grin
    name: GRIN

javatmpdir: '-Djava.io.tmpdir=/mnt/lustre/users/zhangs3/'  # for running java

